version: "3.9"

services:
  assetto-server:
    image: compujuckel/assettoserver:latest
    container_name: AssettoServer
    ports:
      - "9600:9600"
      - "9600:9600/udp"
      - "8081:8081"
    volumes:
      - ./data/:/data
    environment:
      - TZ=Europe/Berlin
    restart: always
